name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      POWERSHELL_TELEMETRY_OPTOUT: 1
      SQLCMD_TELEMETRY: false

    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: ./build.sh
    - name: Test
      run: ./run.cs
      working-directory: ./tests
